### PR TITLE
Add light mode order support

### PR DESCRIPTION
**Pull request by Xuefeng-Zhu**
Fix https://github.com/airswap/airswap-cli/issues/78

### CODE REVIEW

**Comment by dmosites** [comment]
Hi @Xuefeng-Zhu thank you for the contribution. Light orders are filled on their own settlement contract, so the following `swap` would need to switch based on the selected format: https://github.com/airswap/airswap-cli/pull/79/files#diff-2d71f56cfe08932b34f3a1ba0f3da804f4c39417da539c3ccdf3f62615a943adR87

You can import the Light ABI this way:
```
const Light = require('@airswap/light/build/contracts/Light.json')
```

**Comment by Xuefeng-Zhu** [comment]
@dmosites Thanks for review I addressed your comments

**Comment by dmosites** [comment]
Thanks @Xuefeng-Zhu. Looking more closely here, there are several differences between full and light unfortunately.

* A light `order` returned has flat parameters e.g. `signerWallet` vs `signer.wallet`
* The validator will not properly validate a light order, so would need to be skipped
* The `swap` function signature for light is different (spreads out order params)
```function swap(
    uint256 nonce,
    uint256 expiry,
    IERC20 signerToken,
    uint256 signerAmount,
    IERC20 senderToken,
    uint256 senderAmount,
    bytes calldata signature
  )
  ```

This is a good starting point but don't think we can merge in as-is.

**Comment by Xuefeng-Zhu** [comment]
@dmosites Got it. In this case, do you think we need to split it out to a independent command? Or still integrate it into order command?

**Comment by dmosites** [comment]
Likely cleaner to have an independent command, otherwise there will be a lot of conditional logic. Thanks @Xuefeng-Zhu.

**Pull request closed without merging**
